name: Docker Build

on:
  push:
    branches:
      - master # Default release branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
        # Checks out repository so your workflow can access it
    - uses: actions/checkout@v1
    # Use docker login
    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    # Build and push the image to Container Registry
    - name: Build and Push container to registry
      working-directory: CheapAndCheerfulAutoDeploy.WebApp
      run: |
        docker build -t surgicalcoder/cheapandcheerfulautodeploy:${{ github.sha }} .
        docker push surgicalcoder/cheapandcheerfulautodeploy:${{ github.sha }}
